	soc_system u0 (
		.alt_vip_cl_cvo_0_clocked_video_vid_clk       (<connected-to-alt_vip_cl_cvo_0_clocked_video_vid_clk>),       // alt_vip_cl_cvo_0_clocked_video.vid_clk
		.alt_vip_cl_cvo_0_clocked_video_vid_data      (<connected-to-alt_vip_cl_cvo_0_clocked_video_vid_data>),      //                               .vid_data
		.alt_vip_cl_cvo_0_clocked_video_underflow     (<connected-to-alt_vip_cl_cvo_0_clocked_video_underflow>),     //                               .underflow
		.alt_vip_cl_cvo_0_clocked_video_vid_datavalid (<connected-to-alt_vip_cl_cvo_0_clocked_video_vid_datavalid>), //                               .vid_datavalid
		.alt_vip_cl_cvo_0_clocked_video_vid_v_sync    (<connected-to-alt_vip_cl_cvo_0_clocked_video_vid_v_sync>),    //                               .vid_v_sync
		.alt_vip_cl_cvo_0_clocked_video_vid_h_sync    (<connected-to-alt_vip_cl_cvo_0_clocked_video_vid_h_sync>),    //                               .vid_h_sync
		.alt_vip_cl_cvo_0_clocked_video_vid_f         (<connected-to-alt_vip_cl_cvo_0_clocked_video_vid_f>),         //                               .vid_f
		.alt_vip_cl_cvo_0_clocked_video_vid_h         (<connected-to-alt_vip_cl_cvo_0_clocked_video_vid_h>),         //                               .vid_h
		.alt_vip_cl_cvo_0_clocked_video_vid_v         (<connected-to-alt_vip_cl_cvo_0_clocked_video_vid_v>),         //                               .vid_v
		.alt_vip_cl_mixer_0_din1_data                 (<connected-to-alt_vip_cl_mixer_0_din1_data>),                 //        alt_vip_cl_mixer_0_din1.data
		.alt_vip_cl_mixer_0_din1_valid                (<connected-to-alt_vip_cl_mixer_0_din1_valid>),                //                               .valid
		.alt_vip_cl_mixer_0_din1_startofpacket        (<connected-to-alt_vip_cl_mixer_0_din1_startofpacket>),        //                               .startofpacket
		.alt_vip_cl_mixer_0_din1_endofpacket          (<connected-to-alt_vip_cl_mixer_0_din1_endofpacket>),          //                               .endofpacket
		.alt_vip_cl_mixer_0_din1_ready                (<connected-to-alt_vip_cl_mixer_0_din1_ready>),                //                               .ready
		.clk_clk                                      (<connected-to-clk_clk>),                                      //                            clk.clk
		.clk_100m_a_clk                               (<connected-to-clk_100m_a_clk>),                               //                     clk_100m_a.clk
		.clk_hdmi_clk                                 (<connected-to-clk_hdmi_clk>),                                 //                       clk_hdmi.clk
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK        (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>),        //                   hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),          //                               .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),          //                               .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),          //                               .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),          //                               .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),          //                               .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),          //                               .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC           (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),           //                               .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL        (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>),        //                               .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL        (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>),        //                               .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK        (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>),        //                               .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),          //                               .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),          //                               .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3          (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),          //                               .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_sdio_inst_CMD            (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),            //                               .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0             (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),             //                               .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1             (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),             //                               .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK            (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),            //                               .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2             (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),             //                               .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3             (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),             //                               .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0             (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),             //                               .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1             (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),             //                               .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2             (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),             //                               .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3             (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),             //                               .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4             (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),             //                               .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5             (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),             //                               .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6             (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),             //                               .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7             (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),             //                               .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),            //                               .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),            //                               .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),            //                               .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT            (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),            //                               .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK           (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),           //                               .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI          (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),          //                               .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO          (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),          //                               .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0           (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),           //                               .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX            (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),            //                               .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX            (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),            //                               .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA            (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),            //                               .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL            (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),            //                               .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA            (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),            //                               .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL            (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),            //                               .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09         (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),         //                               .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35         (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),         //                               .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40         (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),         //                               .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53         (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),         //                               .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54         (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),         //                               .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61         (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),         //                               .hps_io_gpio_inst_GPIO61
		.memory_mem_a                                 (<connected-to-memory_mem_a>),                                 //                         memory.mem_a
		.memory_mem_ba                                (<connected-to-memory_mem_ba>),                                //                               .mem_ba
		.memory_mem_ck                                (<connected-to-memory_mem_ck>),                                //                               .mem_ck
		.memory_mem_ck_n                              (<connected-to-memory_mem_ck_n>),                              //                               .mem_ck_n
		.memory_mem_cke                               (<connected-to-memory_mem_cke>),                               //                               .mem_cke
		.memory_mem_cs_n                              (<connected-to-memory_mem_cs_n>),                              //                               .mem_cs_n
		.memory_mem_ras_n                             (<connected-to-memory_mem_ras_n>),                             //                               .mem_ras_n
		.memory_mem_cas_n                             (<connected-to-memory_mem_cas_n>),                             //                               .mem_cas_n
		.memory_mem_we_n                              (<connected-to-memory_mem_we_n>),                              //                               .mem_we_n
		.memory_mem_reset_n                           (<connected-to-memory_mem_reset_n>),                           //                               .mem_reset_n
		.memory_mem_dq                                (<connected-to-memory_mem_dq>),                                //                               .mem_dq
		.memory_mem_dqs                               (<connected-to-memory_mem_dqs>),                               //                               .mem_dqs
		.memory_mem_dqs_n                             (<connected-to-memory_mem_dqs_n>),                             //                               .mem_dqs_n
		.memory_mem_odt                               (<connected-to-memory_mem_odt>),                               //                               .mem_odt
		.memory_mem_dm                                (<connected-to-memory_mem_dm>),                                //                               .mem_dm
		.memory_oct_rzqin                             (<connected-to-memory_oct_rzqin>),                             //                               .oct_rzqin
		.mm_bridge_1_s0_waitrequest                   (<connected-to-mm_bridge_1_s0_waitrequest>),                   //                 mm_bridge_1_s0.waitrequest
		.mm_bridge_1_s0_readdata                      (<connected-to-mm_bridge_1_s0_readdata>),                      //                               .readdata
		.mm_bridge_1_s0_readdatavalid                 (<connected-to-mm_bridge_1_s0_readdatavalid>),                 //                               .readdatavalid
		.mm_bridge_1_s0_burstcount                    (<connected-to-mm_bridge_1_s0_burstcount>),                    //                               .burstcount
		.mm_bridge_1_s0_writedata                     (<connected-to-mm_bridge_1_s0_writedata>),                     //                               .writedata
		.mm_bridge_1_s0_address                       (<connected-to-mm_bridge_1_s0_address>),                       //                               .address
		.mm_bridge_1_s0_write                         (<connected-to-mm_bridge_1_s0_write>),                         //                               .write
		.mm_bridge_1_s0_read                          (<connected-to-mm_bridge_1_s0_read>),                          //                               .read
		.mm_bridge_1_s0_byteenable                    (<connected-to-mm_bridge_1_s0_byteenable>),                    //                               .byteenable
		.mm_bridge_1_s0_debugaccess                   (<connected-to-mm_bridge_1_s0_debugaccess>),                   //                               .debugaccess
		.reset_reset                                  (<connected-to-reset_reset>),                                  //                          reset.reset
		.clk_100m_clk                                 (<connected-to-clk_100m_clk>)                                  //                       clk_100m.clk
	);

