#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'ARM_A9_HPS' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'videocard_new_0_memory_main', class 'videocard_new'
 * The macros are prefixed with 'VIDEOCARD_NEW_0_MEMORY_MAIN_'.
 * The prefix is the slave descriptor.
 */
#define VIDEOCARD_NEW_0_MEMORY_MAIN_COMPONENT_TYPE videocard_new
#define VIDEOCARD_NEW_0_MEMORY_MAIN_COMPONENT_NAME videocard_new_0
#define VIDEOCARD_NEW_0_MEMORY_MAIN_BASE 0x0
#define VIDEOCARD_NEW_0_MEMORY_MAIN_SPAN 524288
#define VIDEOCARD_NEW_0_MEMORY_MAIN_END 0x7ffff

/*
 * Macros for device 'videocard_new_0_memory_control', class 'videocard_new'
 * The macros are prefixed with 'VIDEOCARD_NEW_0_MEMORY_CONTROL_'.
 * The prefix is the slave descriptor.
 */
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_COMPONENT_TYPE videocard_new
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_COMPONENT_NAME videocard_new_0
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_BASE 0x0
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_SPAN 8
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_END 0x7

/*
 * Macros for device 'video_dma_0', class 'video_dma'
 * The macros are prefixed with 'VIDEO_DMA_0_'.
 * The prefix is the slave descriptor.
 */
#define VIDEO_DMA_0_COMPONENT_TYPE video_dma
#define VIDEO_DMA_0_COMPONENT_NAME video_dma_0
#define VIDEO_DMA_0_BASE 0x38
#define VIDEO_DMA_0_SPAN 8
#define VIDEO_DMA_0_END 0x3f


#endif /* _ALTERA_HPS_0_H_ */
