// soc_system_mm_interconnect_4.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_4 (
		input  wire        pll_0_outclk2_clk,                                 //                               pll_0_outclk2.clk
		input  wire        our_video_dma_0_reset_reset_bridge_in_reset_reset, // our_video_dma_0_reset_reset_bridge_in_reset.reset
		input  wire [31:0] our_video_dma_0_video_data_reader_address,         //           our_video_dma_0_video_data_reader.address
		output wire        our_video_dma_0_video_data_reader_waitrequest,     //                                            .waitrequest
		input  wire        our_video_dma_0_video_data_reader_read,            //                                            .read
		output wire [31:0] our_video_dma_0_video_data_reader_readdata,        //                                            .readdata
		output wire        our_video_dma_0_video_data_reader_readdatavalid,   //                                            .readdatavalid
		output wire [9:0]  mm_bridge_2_s0_address,                            //                              mm_bridge_2_s0.address
		output wire        mm_bridge_2_s0_write,                              //                                            .write
		output wire        mm_bridge_2_s0_read,                               //                                            .read
		input  wire [31:0] mm_bridge_2_s0_readdata,                           //                                            .readdata
		output wire [31:0] mm_bridge_2_s0_writedata,                          //                                            .writedata
		output wire [0:0]  mm_bridge_2_s0_burstcount,                         //                                            .burstcount
		output wire [3:0]  mm_bridge_2_s0_byteenable,                         //                                            .byteenable
		input  wire        mm_bridge_2_s0_readdatavalid,                      //                                            .readdatavalid
		input  wire        mm_bridge_2_s0_waitrequest,                        //                                            .waitrequest
		output wire        mm_bridge_2_s0_debugaccess                         //                                            .debugaccess
	);

	wire         our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_waitrequest;   // mm_bridge_2_s0_translator:uav_waitrequest -> our_video_dma_0_video_data_reader_translator:uav_waitrequest
	wire  [31:0] our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_readdata;      // mm_bridge_2_s0_translator:uav_readdata -> our_video_dma_0_video_data_reader_translator:uav_readdata
	wire         our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_debugaccess;   // our_video_dma_0_video_data_reader_translator:uav_debugaccess -> mm_bridge_2_s0_translator:uav_debugaccess
	wire  [31:0] our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_address;       // our_video_dma_0_video_data_reader_translator:uav_address -> mm_bridge_2_s0_translator:uav_address
	wire         our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_read;          // our_video_dma_0_video_data_reader_translator:uav_read -> mm_bridge_2_s0_translator:uav_read
	wire   [3:0] our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_byteenable;    // our_video_dma_0_video_data_reader_translator:uav_byteenable -> mm_bridge_2_s0_translator:uav_byteenable
	wire         our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_readdatavalid; // mm_bridge_2_s0_translator:uav_readdatavalid -> our_video_dma_0_video_data_reader_translator:uav_readdatavalid
	wire         our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_lock;          // our_video_dma_0_video_data_reader_translator:uav_lock -> mm_bridge_2_s0_translator:uav_lock
	wire         our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_write;         // our_video_dma_0_video_data_reader_translator:uav_write -> mm_bridge_2_s0_translator:uav_write
	wire  [31:0] our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_writedata;     // our_video_dma_0_video_data_reader_translator:uav_writedata -> mm_bridge_2_s0_translator:uav_writedata
	wire   [2:0] our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_burstcount;    // our_video_dma_0_video_data_reader_translator:uav_burstcount -> mm_bridge_2_s0_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) our_video_dma_0_video_data_reader_translator (
		.clk                    (pll_0_outclk2_clk),                                                                    //                       clk.clk
		.reset                  (our_video_dma_0_reset_reset_bridge_in_reset_reset),                                    //                     reset.reset
		.uav_address            (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (our_video_dma_0_video_data_reader_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (our_video_dma_0_video_data_reader_waitrequest),                                        //                          .waitrequest
		.av_read                (our_video_dma_0_video_data_reader_read),                                               //                          .read
		.av_readdata            (our_video_dma_0_video_data_reader_readdata),                                           //                          .readdata
		.av_readdatavalid       (our_video_dma_0_video_data_reader_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                                                 //               (terminated)
		.av_byteenable          (4'b1111),                                                                              //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                 //               (terminated)
		.av_begintransfer       (1'b0),                                                                                 //               (terminated)
		.av_chipselect          (1'b0),                                                                                 //               (terminated)
		.av_write               (1'b0),                                                                                 //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                                 //               (terminated)
		.av_lock                (1'b0),                                                                                 //               (terminated)
		.av_debugaccess         (1'b0),                                                                                 //               (terminated)
		.uav_clken              (),                                                                                     //               (terminated)
		.av_clken               (1'b1),                                                                                 //               (terminated)
		.uav_response           (2'b00),                                                                                //               (terminated)
		.av_response            (),                                                                                     //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                 //               (terminated)
		.av_writeresponsevalid  ()                                                                                      //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (10),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) mm_bridge_2_s0_translator (
		.clk                    (pll_0_outclk2_clk),                                                                    //                      clk.clk
		.reset                  (our_video_dma_0_reset_reset_bridge_in_reset_reset),                                    //                    reset.reset
		.uav_address            (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (our_video_dma_0_video_data_reader_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (mm_bridge_2_s0_address),                                                               //      avalon_anti_slave_0.address
		.av_write               (mm_bridge_2_s0_write),                                                                 //                         .write
		.av_read                (mm_bridge_2_s0_read),                                                                  //                         .read
		.av_readdata            (mm_bridge_2_s0_readdata),                                                              //                         .readdata
		.av_writedata           (mm_bridge_2_s0_writedata),                                                             //                         .writedata
		.av_burstcount          (mm_bridge_2_s0_burstcount),                                                            //                         .burstcount
		.av_byteenable          (mm_bridge_2_s0_byteenable),                                                            //                         .byteenable
		.av_readdatavalid       (mm_bridge_2_s0_readdatavalid),                                                         //                         .readdatavalid
		.av_waitrequest         (mm_bridge_2_s0_waitrequest),                                                           //                         .waitrequest
		.av_debugaccess         (mm_bridge_2_s0_debugaccess),                                                           //                         .debugaccess
		.av_begintransfer       (),                                                                                     //              (terminated)
		.av_beginbursttransfer  (),                                                                                     //              (terminated)
		.av_writebyteenable     (),                                                                                     //              (terminated)
		.av_lock                (),                                                                                     //              (terminated)
		.av_chipselect          (),                                                                                     //              (terminated)
		.av_clken               (),                                                                                     //              (terminated)
		.uav_clken              (1'b0),                                                                                 //              (terminated)
		.av_outputenable        (),                                                                                     //              (terminated)
		.uav_response           (),                                                                                     //              (terminated)
		.av_response            (2'b00),                                                                                //              (terminated)
		.uav_writeresponsevalid (),                                                                                     //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                  //              (terminated)
	);

endmodule
