#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'ARM_A9_HPS' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'videocard_new_0_memory_main', class 'videocard_new'
 * The macros are prefixed with 'VIDEOCARD_NEW_0_MEMORY_MAIN_'.
 * The prefix is the slave descriptor.
 */
#define VIDEOCARD_NEW_0_MEMORY_MAIN_COMPONENT_TYPE videocard_new
#define VIDEOCARD_NEW_0_MEMORY_MAIN_COMPONENT_NAME videocard_new_0
#define VIDEOCARD_NEW_0_MEMORY_MAIN_BASE 0x0
#define VIDEOCARD_NEW_0_MEMORY_MAIN_SPAN 524288
#define VIDEOCARD_NEW_0_MEMORY_MAIN_END 0x7ffff

/*
 * Macros for device 'videocard_new_0_memory_control', class 'videocard_new'
 * The macros are prefixed with 'VIDEOCARD_NEW_0_MEMORY_CONTROL_'.
 * The prefix is the slave descriptor.
 */
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_COMPONENT_TYPE videocard_new
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_COMPONENT_NAME videocard_new_0
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_BASE 0x0
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_SPAN 2
#define VIDEOCARD_NEW_0_MEMORY_CONTROL_END 0x1

/*
 * Macros for device 'alt_vip_cl_mixer_0', class 'alt_vip_cl_mixer'
 * The macros are prefixed with 'ALT_VIP_CL_MIXER_0_'.
 * The prefix is the slave descriptor.
 */
#define ALT_VIP_CL_MIXER_0_COMPONENT_TYPE alt_vip_cl_mixer
#define ALT_VIP_CL_MIXER_0_COMPONENT_NAME alt_vip_cl_mixer_0
#define ALT_VIP_CL_MIXER_0_BASE 0x80000
#define ALT_VIP_CL_MIXER_0_SPAN 512
#define ALT_VIP_CL_MIXER_0_END 0x801ff

/*
 * Macros for device 'dma_0', class 'altera_avalon_dma'
 * The macros are prefixed with 'DMA_0_'.
 * The prefix is the slave descriptor.
 */
#define DMA_0_COMPONENT_TYPE altera_avalon_dma
#define DMA_0_COMPONENT_NAME dma_0
#define DMA_0_BASE 0x80200
#define DMA_0_SPAN 32
#define DMA_0_END 0x8021f
#define DMA_0_ALLOW_BYTE_TRANSACTIONS 0
#define DMA_0_ALLOW_DOUBLEWORD_TRANSACTIONS 0
#define DMA_0_ALLOW_HW_TRANSACTIONS 0
#define DMA_0_ALLOW_QUADWORD_TRANSACTIONS 0
#define DMA_0_ALLOW_WORD_TRANSACTIONS 1
#define DMA_0_LENGTHWIDTH 16
#define DMA_0_MAX_BURST_SIZE 128

/*
 * Macros for device 'ARM_A9_HPS_axi_sdram', class 'axi_sdram'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_COMPONENT_TYPE axi_sdram
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_COMPONENT_NAME ARM_A9_HPS_axi_sdram
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_BASE 0x0
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_SPAN 0x80000000
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_END 0x7fffffff
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_SIZE_MULTIPLE 1
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_SIZE_VALUE 1<<31
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_WRITABLE 1
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_MEMORY_INFO_GENERATE_DAT_SYM 0
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_MEMORY_INFO_GENERATE_HEX 0
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_SDRAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 31

/*
 * Macros for device 'ARM_A9_HPS_gmac0', class 'stmmac'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_GMAC0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC0_COMPONENT_TYPE stmmac
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC0_COMPONENT_NAME ARM_A9_HPS_gmac0
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC0_BASE 0xff700000
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC0_SPAN 8192
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC0_END 0xff701fff

/*
 * Macros for device 'ARM_A9_HPS_gmac1', class 'stmmac'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_GMAC1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC1_COMPONENT_TYPE stmmac
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC1_COMPONENT_NAME ARM_A9_HPS_gmac1
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC1_BASE 0xff702000
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC1_SPAN 8192
#define DMA_0_READ_MASTER_ARM_A9_HPS_GMAC1_END 0xff703fff

/*
 * Macros for device 'ARM_A9_HPS_sdmmc', class 'sdmmc'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_SDMMC_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDMMC_COMPONENT_TYPE sdmmc
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDMMC_COMPONENT_NAME ARM_A9_HPS_sdmmc
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDMMC_BASE 0xff704000
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDMMC_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDMMC_END 0xff704fff

/*
 * Macros for device 'ARM_A9_HPS_qspi', class 'cadence_qspi'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_QSPI_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_QSPI_COMPONENT_TYPE cadence_qspi
#define DMA_0_READ_MASTER_ARM_A9_HPS_QSPI_COMPONENT_NAME ARM_A9_HPS_qspi
#define DMA_0_READ_MASTER_ARM_A9_HPS_QSPI_BASE 0xff705000
#define DMA_0_READ_MASTER_ARM_A9_HPS_QSPI_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_QSPI_END 0xff7050ff

/*
 * Macros for device 'ARM_A9_HPS_fpgamgr', class 'altera_fpgamgr'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_FPGAMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_FPGAMGR_COMPONENT_TYPE altera_fpgamgr
#define DMA_0_READ_MASTER_ARM_A9_HPS_FPGAMGR_COMPONENT_NAME ARM_A9_HPS_fpgamgr
#define DMA_0_READ_MASTER_ARM_A9_HPS_FPGAMGR_BASE 0xff706000
#define DMA_0_READ_MASTER_ARM_A9_HPS_FPGAMGR_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_FPGAMGR_END 0xff706fff

/*
 * Macros for device 'ARM_A9_HPS_gpio0', class 'dw_gpio'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_GPIO0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO0_COMPONENT_TYPE dw_gpio
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO0_COMPONENT_NAME ARM_A9_HPS_gpio0
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO0_BASE 0xff708000
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO0_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO0_END 0xff7080ff

/*
 * Macros for device 'ARM_A9_HPS_gpio1', class 'dw_gpio'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_GPIO1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO1_COMPONENT_TYPE dw_gpio
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO1_COMPONENT_NAME ARM_A9_HPS_gpio1
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO1_BASE 0xff709000
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO1_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO1_END 0xff7090ff

/*
 * Macros for device 'ARM_A9_HPS_gpio2', class 'dw_gpio'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_GPIO2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO2_COMPONENT_TYPE dw_gpio
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO2_COMPONENT_NAME ARM_A9_HPS_gpio2
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO2_BASE 0xff70a000
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO2_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_GPIO2_END 0xff70a0ff

/*
 * Macros for device 'ARM_A9_HPS_l3regs', class 'altera_l3regs'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_L3REGS_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_L3REGS_COMPONENT_TYPE altera_l3regs
#define DMA_0_READ_MASTER_ARM_A9_HPS_L3REGS_COMPONENT_NAME ARM_A9_HPS_l3regs
#define DMA_0_READ_MASTER_ARM_A9_HPS_L3REGS_BASE 0xff800000
#define DMA_0_READ_MASTER_ARM_A9_HPS_L3REGS_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_L3REGS_END 0xff800fff

/*
 * Macros for device 'ARM_A9_HPS_nand0', class 'denali_nand'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_NAND0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_NAND0_COMPONENT_TYPE denali_nand
#define DMA_0_READ_MASTER_ARM_A9_HPS_NAND0_COMPONENT_NAME ARM_A9_HPS_nand0
#define DMA_0_READ_MASTER_ARM_A9_HPS_NAND0_BASE 0xff900000
#define DMA_0_READ_MASTER_ARM_A9_HPS_NAND0_SPAN 65536
#define DMA_0_READ_MASTER_ARM_A9_HPS_NAND0_END 0xff90ffff

/*
 * Macros for device 'ARM_A9_HPS_usb0', class 'usb'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_USB0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB0_COMPONENT_TYPE usb
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB0_COMPONENT_NAME ARM_A9_HPS_usb0
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB0_BASE 0xffb00000
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB0_SPAN 262144
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB0_END 0xffb3ffff

/*
 * Macros for device 'ARM_A9_HPS_usb1', class 'usb'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_USB1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB1_COMPONENT_TYPE usb
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB1_COMPONENT_NAME ARM_A9_HPS_usb1
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB1_BASE 0xffb40000
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB1_SPAN 262144
#define DMA_0_READ_MASTER_ARM_A9_HPS_USB1_END 0xffb7ffff

/*
 * Macros for device 'ARM_A9_HPS_dcan0', class 'bosch_dcan'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_DCAN0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN0_COMPONENT_TYPE bosch_dcan
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN0_COMPONENT_NAME ARM_A9_HPS_dcan0
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN0_BASE 0xffc00000
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN0_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN0_END 0xffc00fff

/*
 * Macros for device 'ARM_A9_HPS_dcan1', class 'bosch_dcan'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_DCAN1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN1_COMPONENT_TYPE bosch_dcan
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN1_COMPONENT_NAME ARM_A9_HPS_dcan1
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN1_BASE 0xffc01000
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN1_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_DCAN1_END 0xffc01fff

/*
 * Macros for device 'ARM_A9_HPS_uart0', class 'snps_uart'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_UART0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_COMPONENT_TYPE snps_uart
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_COMPONENT_NAME ARM_A9_HPS_uart0
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_BASE 0xffc02000
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_END 0xffc020ff
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_FIFO_DEPTH 128
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_FIFO_HWFC 0
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_FIFO_MODE 1
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_FIFO_SWFC 0
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART0_FREQ 100000000

/*
 * Macros for device 'ARM_A9_HPS_uart1', class 'snps_uart'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_UART1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_COMPONENT_TYPE snps_uart
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_COMPONENT_NAME ARM_A9_HPS_uart1
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_BASE 0xffc03000
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_END 0xffc030ff
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_FIFO_DEPTH 128
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_FIFO_HWFC 0
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_FIFO_MODE 1
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_FIFO_SWFC 0
#define DMA_0_READ_MASTER_ARM_A9_HPS_UART1_FREQ 100000000

/*
 * Macros for device 'ARM_A9_HPS_i2c0', class 'designware_i2c'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_I2C0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C0_COMPONENT_TYPE designware_i2c
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C0_COMPONENT_NAME ARM_A9_HPS_i2c0
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C0_BASE 0xffc04000
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C0_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C0_END 0xffc040ff

/*
 * Macros for device 'ARM_A9_HPS_i2c1', class 'designware_i2c'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_I2C1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C1_COMPONENT_TYPE designware_i2c
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C1_COMPONENT_NAME ARM_A9_HPS_i2c1
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C1_BASE 0xffc05000
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C1_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C1_END 0xffc050ff

/*
 * Macros for device 'ARM_A9_HPS_i2c2', class 'designware_i2c'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_I2C2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C2_COMPONENT_TYPE designware_i2c
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C2_COMPONENT_NAME ARM_A9_HPS_i2c2
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C2_BASE 0xffc06000
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C2_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C2_END 0xffc060ff

/*
 * Macros for device 'ARM_A9_HPS_i2c3', class 'designware_i2c'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_I2C3_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C3_COMPONENT_TYPE designware_i2c
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C3_COMPONENT_NAME ARM_A9_HPS_i2c3
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C3_BASE 0xffc07000
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C3_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_I2C3_END 0xffc070ff

/*
 * Macros for device 'ARM_A9_HPS_timer0', class 'dw_apb_timer_sp'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_TIMER0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER0_COMPONENT_TYPE dw_apb_timer_sp
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER0_COMPONENT_NAME ARM_A9_HPS_timer0
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER0_BASE 0xffc08000
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER0_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER0_END 0xffc080ff

/*
 * Macros for device 'ARM_A9_HPS_timer1', class 'dw_apb_timer_sp'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_TIMER1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER1_COMPONENT_TYPE dw_apb_timer_sp
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER1_COMPONENT_NAME ARM_A9_HPS_timer1
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER1_BASE 0xffc09000
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER1_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER1_END 0xffc090ff

/*
 * Macros for device 'ARM_A9_HPS_sdrctl', class 'altera_sdrctl'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_SDRCTL_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDRCTL_COMPONENT_TYPE altera_sdrctl
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDRCTL_COMPONENT_NAME ARM_A9_HPS_sdrctl
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDRCTL_BASE 0xffc25000
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDRCTL_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_SDRCTL_END 0xffc25fff

/*
 * Macros for device 'ARM_A9_HPS_timer2', class 'dw_apb_timer_osc'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_TIMER2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER2_COMPONENT_TYPE dw_apb_timer_osc
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER2_COMPONENT_NAME ARM_A9_HPS_timer2
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER2_BASE 0xffd00000
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER2_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER2_END 0xffd000ff

/*
 * Macros for device 'ARM_A9_HPS_timer3', class 'dw_apb_timer_osc'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_TIMER3_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER3_COMPONENT_TYPE dw_apb_timer_osc
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER3_COMPONENT_NAME ARM_A9_HPS_timer3
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER3_BASE 0xffd01000
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER3_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER3_END 0xffd010ff

/*
 * Macros for device 'ARM_A9_HPS_clkmgr', class 'asimov_clkmgr'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_CLKMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_CLKMGR_COMPONENT_TYPE asimov_clkmgr
#define DMA_0_READ_MASTER_ARM_A9_HPS_CLKMGR_COMPONENT_NAME ARM_A9_HPS_clkmgr
#define DMA_0_READ_MASTER_ARM_A9_HPS_CLKMGR_BASE 0xffd04000
#define DMA_0_READ_MASTER_ARM_A9_HPS_CLKMGR_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_CLKMGR_END 0xffd04fff

/*
 * Macros for device 'ARM_A9_HPS_rstmgr', class 'altera_rstmgr'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_RSTMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_RSTMGR_COMPONENT_TYPE altera_rstmgr
#define DMA_0_READ_MASTER_ARM_A9_HPS_RSTMGR_COMPONENT_NAME ARM_A9_HPS_rstmgr
#define DMA_0_READ_MASTER_ARM_A9_HPS_RSTMGR_BASE 0xffd05000
#define DMA_0_READ_MASTER_ARM_A9_HPS_RSTMGR_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_RSTMGR_END 0xffd050ff

/*
 * Macros for device 'ARM_A9_HPS_sysmgr', class 'altera_sysmgr'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_SYSMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_SYSMGR_COMPONENT_TYPE altera_sysmgr
#define DMA_0_READ_MASTER_ARM_A9_HPS_SYSMGR_COMPONENT_NAME ARM_A9_HPS_sysmgr
#define DMA_0_READ_MASTER_ARM_A9_HPS_SYSMGR_BASE 0xffd08000
#define DMA_0_READ_MASTER_ARM_A9_HPS_SYSMGR_SPAN 1024
#define DMA_0_READ_MASTER_ARM_A9_HPS_SYSMGR_END 0xffd083ff

/*
 * Macros for device 'ARM_A9_HPS_dma', class 'arm_pl330_dma'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_DMA_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_DMA_COMPONENT_TYPE arm_pl330_dma
#define DMA_0_READ_MASTER_ARM_A9_HPS_DMA_COMPONENT_NAME ARM_A9_HPS_dma
#define DMA_0_READ_MASTER_ARM_A9_HPS_DMA_BASE 0xffe01000
#define DMA_0_READ_MASTER_ARM_A9_HPS_DMA_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_DMA_END 0xffe01fff

/*
 * Macros for device 'ARM_A9_HPS_spim0', class 'spi'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_SPIM0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM0_COMPONENT_TYPE spi
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM0_COMPONENT_NAME ARM_A9_HPS_spim0
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM0_BASE 0xfff00000
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM0_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM0_END 0xfff000ff

/*
 * Macros for device 'ARM_A9_HPS_spim1', class 'spi'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_SPIM1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM1_COMPONENT_TYPE spi
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM1_COMPONENT_NAME ARM_A9_HPS_spim1
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM1_BASE 0xfff01000
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM1_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_SPIM1_END 0xfff010ff

/*
 * Macros for device 'ARM_A9_HPS_timer', class 'arm_internal_timer'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_TIMER_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER_COMPONENT_TYPE arm_internal_timer
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER_COMPONENT_NAME ARM_A9_HPS_timer
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER_BASE 0xfffec600
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER_SPAN 256
#define DMA_0_READ_MASTER_ARM_A9_HPS_TIMER_END 0xfffec6ff

/*
 * Macros for device 'ARM_A9_HPS_arm_gic_0', class 'arm_gic'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_ARM_GIC_0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_ARM_GIC_0_COMPONENT_TYPE arm_gic
#define DMA_0_READ_MASTER_ARM_A9_HPS_ARM_GIC_0_COMPONENT_NAME ARM_A9_HPS_arm_gic_0
#define DMA_0_READ_MASTER_ARM_A9_HPS_ARM_GIC_0_BASE 0xfffed000
#define DMA_0_READ_MASTER_ARM_A9_HPS_ARM_GIC_0_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_ARM_GIC_0_END 0xfffedfff

/*
 * Macros for device 'ARM_A9_HPS_L2', class 'arm_pl310_L2'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_L2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_L2_COMPONENT_TYPE arm_pl310_L2
#define DMA_0_READ_MASTER_ARM_A9_HPS_L2_COMPONENT_NAME ARM_A9_HPS_L2
#define DMA_0_READ_MASTER_ARM_A9_HPS_L2_BASE 0xfffef000
#define DMA_0_READ_MASTER_ARM_A9_HPS_L2_SPAN 4096
#define DMA_0_READ_MASTER_ARM_A9_HPS_L2_END 0xfffeffff

/*
 * Macros for device 'ARM_A9_HPS_axi_ocram', class 'axi_ocram'
 * Path to the device is from the master group 'dma_0_read_master'.
 * The macros are prefixed with 'DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_COMPONENT_TYPE axi_ocram
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_COMPONENT_NAME ARM_A9_HPS_axi_ocram
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_BASE 0xffff0000
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_SPAN 65536
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_END 0xffffffff
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_SIZE_MULTIPLE 1
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_SIZE_VALUE 1<<16
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_WRITABLE 1
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_MEMORY_INFO_GENERATE_DAT_SYM 0
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_MEMORY_INFO_GENERATE_HEX 0
#define DMA_0_READ_MASTER_ARM_A9_HPS_AXI_OCRAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16

/*
 * Macros for device 'video_dma', class 'altera_up_avalon_video_pixel_buffer_dma'
 * The macros are prefixed with 'VIDEO_DMA_'.
 * The prefix is the slave descriptor.
 */
#define VIDEO_DMA_COMPONENT_TYPE altera_up_avalon_video_pixel_buffer_dma
#define VIDEO_DMA_COMPONENT_NAME video_dma
#define VIDEO_DMA_BASE 0x80220
#define VIDEO_DMA_SPAN 16
#define VIDEO_DMA_END 0x8022f


#endif /* _ALTERA_HPS_0_H_ */
