// Copyright (C) 2019  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 19.1 (Build Build 670 09/22/2019)
// Created on Mon Jan 11 20:21:06 2021

Components Components_inst
(
	.wren(wren_sig) ,	// input  wren_sig
	.clock_reference(clock_reference_sig) ,	// input  clock_reference_sig
	.clock_reset(clock_reset_sig) ,	// input  clock_reset_sig
	.vga_reset(vga_reset_sig) ,	// input  vga_reset_sig
	.adress(adress_sig) ,	// input [22:0] adress_sig
	.hsync(hsync_sig) ,	// output  hsync_sig
	.vsync(vsync_sig) ,	// output  vsync_sig
	.p_tick(p_tick_sig) ,	// output  p_tick_sig
	.blue(blue_sig) ,	// output [4:0] blue_sig
	.data(data_sig) ,	// inout [7:0] data_sig
	.green(green_sig) ,	// output [4:0] green_sig
	.red(red_sig) 	// output [5:0] red_sig
);

