// soc_system_mm_interconnect_5.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_5 (
		input  wire        pll_0_outclk4_clk,                                       //                                     pll_0_outclk4.clk
		input  wire        on_chip_to_dma_bridge_reset_reset_bridge_in_reset_reset, // on_chip_to_dma_bridge_reset_reset_bridge_in_reset.reset
		input  wire [14:0] on_chip_to_dma_bridge_m0_address,                        //                          on_chip_to_dma_bridge_m0.address
		output wire        on_chip_to_dma_bridge_m0_waitrequest,                    //                                                  .waitrequest
		input  wire [0:0]  on_chip_to_dma_bridge_m0_burstcount,                     //                                                  .burstcount
		input  wire [3:0]  on_chip_to_dma_bridge_m0_byteenable,                     //                                                  .byteenable
		input  wire        on_chip_to_dma_bridge_m0_read,                           //                                                  .read
		output wire [31:0] on_chip_to_dma_bridge_m0_readdata,                       //                                                  .readdata
		output wire        on_chip_to_dma_bridge_m0_readdatavalid,                  //                                                  .readdatavalid
		input  wire        on_chip_to_dma_bridge_m0_write,                          //                                                  .write
		input  wire [31:0] on_chip_to_dma_bridge_m0_writedata,                      //                                                  .writedata
		input  wire        on_chip_to_dma_bridge_m0_debugaccess,                    //                                                  .debugaccess
		output wire [12:0] video_buffer_s2_address,                                 //                                   video_buffer_s2.address
		output wire        video_buffer_s2_write,                                   //                                                  .write
		input  wire [31:0] video_buffer_s2_readdata,                                //                                                  .readdata
		output wire [31:0] video_buffer_s2_writedata,                               //                                                  .writedata
		output wire [3:0]  video_buffer_s2_byteenable,                              //                                                  .byteenable
		output wire        video_buffer_s2_chipselect,                              //                                                  .chipselect
		output wire        video_buffer_s2_clken                                    //                                                  .clken
	);

	wire         on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_waitrequest;   // video_buffer_s2_translator:uav_waitrequest -> on_chip_to_dma_bridge_m0_translator:uav_waitrequest
	wire  [31:0] on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_readdata;      // video_buffer_s2_translator:uav_readdata -> on_chip_to_dma_bridge_m0_translator:uav_readdata
	wire         on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_debugaccess;   // on_chip_to_dma_bridge_m0_translator:uav_debugaccess -> video_buffer_s2_translator:uav_debugaccess
	wire  [14:0] on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_address;       // on_chip_to_dma_bridge_m0_translator:uav_address -> video_buffer_s2_translator:uav_address
	wire         on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_read;          // on_chip_to_dma_bridge_m0_translator:uav_read -> video_buffer_s2_translator:uav_read
	wire   [3:0] on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_byteenable;    // on_chip_to_dma_bridge_m0_translator:uav_byteenable -> video_buffer_s2_translator:uav_byteenable
	wire         on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_readdatavalid; // video_buffer_s2_translator:uav_readdatavalid -> on_chip_to_dma_bridge_m0_translator:uav_readdatavalid
	wire         on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_lock;          // on_chip_to_dma_bridge_m0_translator:uav_lock -> video_buffer_s2_translator:uav_lock
	wire         on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_write;         // on_chip_to_dma_bridge_m0_translator:uav_write -> video_buffer_s2_translator:uav_write
	wire  [31:0] on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_writedata;     // on_chip_to_dma_bridge_m0_translator:uav_writedata -> video_buffer_s2_translator:uav_writedata
	wire   [2:0] on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_burstcount;    // on_chip_to_dma_bridge_m0_translator:uav_burstcount -> video_buffer_s2_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (15),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (15),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) on_chip_to_dma_bridge_m0_translator (
		.clk                    (pll_0_outclk4_clk),                                                           //                       clk.clk
		.reset                  (on_chip_to_dma_bridge_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (on_chip_to_dma_bridge_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (on_chip_to_dma_bridge_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (on_chip_to_dma_bridge_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (on_chip_to_dma_bridge_m0_byteenable),                                         //                          .byteenable
		.av_read                (on_chip_to_dma_bridge_m0_read),                                               //                          .read
		.av_readdata            (on_chip_to_dma_bridge_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (on_chip_to_dma_bridge_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (on_chip_to_dma_bridge_m0_write),                                              //                          .write
		.av_writedata           (on_chip_to_dma_bridge_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (on_chip_to_dma_bridge_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                                        //               (terminated)
		.av_begintransfer       (1'b0),                                                                        //               (terminated)
		.av_chipselect          (1'b0),                                                                        //               (terminated)
		.av_lock                (1'b0),                                                                        //               (terminated)
		.uav_clken              (),                                                                            //               (terminated)
		.av_clken               (1'b1),                                                                        //               (terminated)
		.uav_response           (2'b00),                                                                       //               (terminated)
		.av_response            (),                                                                            //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                        //               (terminated)
		.av_writeresponsevalid  ()                                                                             //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (13),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (15),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) video_buffer_s2_translator (
		.clk                    (pll_0_outclk4_clk),                                                           //                      clk.clk
		.reset                  (on_chip_to_dma_bridge_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (on_chip_to_dma_bridge_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (video_buffer_s2_address),                                                     //      avalon_anti_slave_0.address
		.av_write               (video_buffer_s2_write),                                                       //                         .write
		.av_readdata            (video_buffer_s2_readdata),                                                    //                         .readdata
		.av_writedata           (video_buffer_s2_writedata),                                                   //                         .writedata
		.av_byteenable          (video_buffer_s2_byteenable),                                                  //                         .byteenable
		.av_chipselect          (video_buffer_s2_chipselect),                                                  //                         .chipselect
		.av_clken               (video_buffer_s2_clken),                                                       //                         .clken
		.av_read                (),                                                                            //              (terminated)
		.av_begintransfer       (),                                                                            //              (terminated)
		.av_beginbursttransfer  (),                                                                            //              (terminated)
		.av_burstcount          (),                                                                            //              (terminated)
		.av_readdatavalid       (1'b0),                                                                        //              (terminated)
		.av_waitrequest         (1'b0),                                                                        //              (terminated)
		.av_writebyteenable     (),                                                                            //              (terminated)
		.av_lock                (),                                                                            //              (terminated)
		.uav_clken              (1'b0),                                                                        //              (terminated)
		.av_debugaccess         (),                                                                            //              (terminated)
		.av_outputenable        (),                                                                            //              (terminated)
		.uav_response           (),                                                                            //              (terminated)
		.av_response            (2'b00),                                                                       //              (terminated)
		.uav_writeresponsevalid (),                                                                            //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                         //              (terminated)
	);

endmodule
