// soc_system_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_0 (
		input  wire        pll_0_outclk4_clk,                             //                           pll_0_outclk4.clk
		input  wire        video_dma_0_reset_reset_bridge_in_reset_reset, // video_dma_0_reset_reset_bridge_in_reset.reset
		input  wire [31:0] video_dma_0_avalon_master_address,             //               video_dma_0_avalon_master.address
		output wire        video_dma_0_avalon_master_waitrequest,         //                                        .waitrequest
		input  wire        video_dma_0_avalon_master_read,                //                                        .read
		output wire [31:0] video_dma_0_avalon_master_readdata,            //                                        .readdata
		output wire        video_dma_0_avalon_master_readdatavalid,       //                                        .readdatavalid
		output wire [14:0] on_chip_to_dma_bridge_s0_address,              //                on_chip_to_dma_bridge_s0.address
		output wire        on_chip_to_dma_bridge_s0_write,                //                                        .write
		output wire        on_chip_to_dma_bridge_s0_read,                 //                                        .read
		input  wire [31:0] on_chip_to_dma_bridge_s0_readdata,             //                                        .readdata
		output wire [31:0] on_chip_to_dma_bridge_s0_writedata,            //                                        .writedata
		output wire [0:0]  on_chip_to_dma_bridge_s0_burstcount,           //                                        .burstcount
		output wire [3:0]  on_chip_to_dma_bridge_s0_byteenable,           //                                        .byteenable
		input  wire        on_chip_to_dma_bridge_s0_readdatavalid,        //                                        .readdatavalid
		input  wire        on_chip_to_dma_bridge_s0_waitrequest,          //                                        .waitrequest
		output wire        on_chip_to_dma_bridge_s0_debugaccess           //                                        .debugaccess
	);

	wire         video_dma_0_avalon_master_translator_avalon_universal_master_0_waitrequest;   // on_chip_to_dma_bridge_s0_translator:uav_waitrequest -> video_dma_0_avalon_master_translator:uav_waitrequest
	wire  [31:0] video_dma_0_avalon_master_translator_avalon_universal_master_0_readdata;      // on_chip_to_dma_bridge_s0_translator:uav_readdata -> video_dma_0_avalon_master_translator:uav_readdata
	wire         video_dma_0_avalon_master_translator_avalon_universal_master_0_debugaccess;   // video_dma_0_avalon_master_translator:uav_debugaccess -> on_chip_to_dma_bridge_s0_translator:uav_debugaccess
	wire  [31:0] video_dma_0_avalon_master_translator_avalon_universal_master_0_address;       // video_dma_0_avalon_master_translator:uav_address -> on_chip_to_dma_bridge_s0_translator:uav_address
	wire         video_dma_0_avalon_master_translator_avalon_universal_master_0_read;          // video_dma_0_avalon_master_translator:uav_read -> on_chip_to_dma_bridge_s0_translator:uav_read
	wire   [3:0] video_dma_0_avalon_master_translator_avalon_universal_master_0_byteenable;    // video_dma_0_avalon_master_translator:uav_byteenable -> on_chip_to_dma_bridge_s0_translator:uav_byteenable
	wire         video_dma_0_avalon_master_translator_avalon_universal_master_0_readdatavalid; // on_chip_to_dma_bridge_s0_translator:uav_readdatavalid -> video_dma_0_avalon_master_translator:uav_readdatavalid
	wire         video_dma_0_avalon_master_translator_avalon_universal_master_0_lock;          // video_dma_0_avalon_master_translator:uav_lock -> on_chip_to_dma_bridge_s0_translator:uav_lock
	wire         video_dma_0_avalon_master_translator_avalon_universal_master_0_write;         // video_dma_0_avalon_master_translator:uav_write -> on_chip_to_dma_bridge_s0_translator:uav_write
	wire  [31:0] video_dma_0_avalon_master_translator_avalon_universal_master_0_writedata;     // video_dma_0_avalon_master_translator:uav_writedata -> on_chip_to_dma_bridge_s0_translator:uav_writedata
	wire   [2:0] video_dma_0_avalon_master_translator_avalon_universal_master_0_burstcount;    // video_dma_0_avalon_master_translator:uav_burstcount -> on_chip_to_dma_bridge_s0_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) video_dma_0_avalon_master_translator (
		.clk                    (pll_0_outclk4_clk),                                                            //                       clk.clk
		.reset                  (video_dma_0_reset_reset_bridge_in_reset_reset),                                //                     reset.reset
		.uav_address            (video_dma_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (video_dma_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (video_dma_0_avalon_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (video_dma_0_avalon_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (video_dma_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (video_dma_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (video_dma_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (video_dma_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (video_dma_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (video_dma_0_avalon_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (video_dma_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (video_dma_0_avalon_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (video_dma_0_avalon_master_waitrequest),                                        //                          .waitrequest
		.av_read                (video_dma_0_avalon_master_read),                                               //                          .read
		.av_readdata            (video_dma_0_avalon_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (video_dma_0_avalon_master_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                                         //               (terminated)
		.av_byteenable          (4'b1111),                                                                      //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                         //               (terminated)
		.av_begintransfer       (1'b0),                                                                         //               (terminated)
		.av_chipselect          (1'b0),                                                                         //               (terminated)
		.av_write               (1'b0),                                                                         //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                         //               (terminated)
		.av_lock                (1'b0),                                                                         //               (terminated)
		.av_debugaccess         (1'b0),                                                                         //               (terminated)
		.uav_clken              (),                                                                             //               (terminated)
		.av_clken               (1'b1),                                                                         //               (terminated)
		.uav_response           (2'b00),                                                                        //               (terminated)
		.av_response            (),                                                                             //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                         //               (terminated)
		.av_writeresponsevalid  ()                                                                              //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (15),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) on_chip_to_dma_bridge_s0_translator (
		.clk                    (pll_0_outclk4_clk),                                                            //                      clk.clk
		.reset                  (video_dma_0_reset_reset_bridge_in_reset_reset),                                //                    reset.reset
		.uav_address            (video_dma_0_avalon_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (video_dma_0_avalon_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (video_dma_0_avalon_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (video_dma_0_avalon_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (video_dma_0_avalon_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (video_dma_0_avalon_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (video_dma_0_avalon_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (video_dma_0_avalon_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (video_dma_0_avalon_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (video_dma_0_avalon_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (video_dma_0_avalon_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (on_chip_to_dma_bridge_s0_address),                                             //      avalon_anti_slave_0.address
		.av_write               (on_chip_to_dma_bridge_s0_write),                                               //                         .write
		.av_read                (on_chip_to_dma_bridge_s0_read),                                                //                         .read
		.av_readdata            (on_chip_to_dma_bridge_s0_readdata),                                            //                         .readdata
		.av_writedata           (on_chip_to_dma_bridge_s0_writedata),                                           //                         .writedata
		.av_burstcount          (on_chip_to_dma_bridge_s0_burstcount),                                          //                         .burstcount
		.av_byteenable          (on_chip_to_dma_bridge_s0_byteenable),                                          //                         .byteenable
		.av_readdatavalid       (on_chip_to_dma_bridge_s0_readdatavalid),                                       //                         .readdatavalid
		.av_waitrequest         (on_chip_to_dma_bridge_s0_waitrequest),                                         //                         .waitrequest
		.av_debugaccess         (on_chip_to_dma_bridge_s0_debugaccess),                                         //                         .debugaccess
		.av_begintransfer       (),                                                                             //              (terminated)
		.av_beginbursttransfer  (),                                                                             //              (terminated)
		.av_writebyteenable     (),                                                                             //              (terminated)
		.av_lock                (),                                                                             //              (terminated)
		.av_chipselect          (),                                                                             //              (terminated)
		.av_clken               (),                                                                             //              (terminated)
		.uav_clken              (1'b0),                                                                         //              (terminated)
		.av_outputenable        (),                                                                             //              (terminated)
		.uav_response           (),                                                                             //              (terminated)
		.av_response            (2'b00),                                                                        //              (terminated)
		.uav_writeresponsevalid (),                                                                             //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                          //              (terminated)
	);

endmodule
